message("SDK_NAME = ${SDK_NAME}")
message("ARCHS = ${ARCHS}")
message("Using C compiler: ${CMAKE_C_COMPILER}")
message("Using CXX compiler: ${CMAKE_CXX_COMPILER}")


if("${CMAKE_SYSTEM_NAME}" STREQUAL "Android")
    message("ANDROID_HOME: $ENV{ANDROID_HOME}")
    message("CMAKE_ANDROID_ARCH_ABI = ${CMAKE_ANDROID_ARCH_ABI}")
    message("CMAKE_ANDROID_STL_TYPE = ${CMAKE_ANDROID_STL_TYPE}")
    message("CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION = ${CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION}")
    message("CMAKE_SYSTEM_PROCESSOR = ${CMAKE_SYSTEM_PROCESSOR}")
    message("CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")
    message("CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
    message("CMAKE_CXX_COMPILER_TARGET = ${CMAKE_CXX_COMPILER_TARGET}")
    message("CMAKE_C_COMPILER_TARGET = ${CMAKE_C_COMPILER_TARGET}")
    message("CMAKE_SYSTEM_NAME = ${CMAKE_SYSTEM_NAME}")
    if(NOT $ENV{ANDROID_HOME} STREQUAL "")
        message("CMAKE_ANDROID_NDK = $ENV{ANDROID_HOME}/ndk-bundle")
    else()
        message(FATAL_ERROR "Failed to determine CMAKE_ANDROID_NDK. Is ANDROID_HOME set?" )
    endif()
    if (APPLE)
        message("编译平台系统是APPLE")
    endif ()
endif ()

if (CMAKE_SYSTEM_NAME MATCHES Android)
    add_compile_definitions(IS_ANDROID=1)
endif ()


if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(IS_LINUX TRUE)
elseif(CMAKE_SYSTEM_NAME MATCHES "Android")
    set(IS_ANDROID TRUE)
elseif(WIN32)
elseif(APPLE)
elseif(FUCHSIA)
else()
    message(FATAL_ERROR "Platform is not supported")
endif()
message("IS_ANDROID = ${IS_ANDROID}")

message("CMAKE_OSX_ARCHITECTURES = ${CMAKE_OSX_ARCHITECTURES}")
message("ANDROID_PLATFORM = ${ANDROID_PLATFORM}")
message("ANDROID_ABI = ${ANDROID_ABI}")