set(FOREVER_DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/third_party)

message("PROJECT_SOURCE_DIR: ${PROJECT_SOURCE_DIR}")
message("PROJECT_BINARY_DIR: ${PROJECT_BINARY_DIR}")
message("FOREVER_DOWNLOAD_DIR: ${FOREVER_DOWNLOAD_DIR}")
message("CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}")
message("CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
